### PR TITLE
CS update with PHP-CS-Fixer - WIP - just playing around

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Fix issues with PHP-CS-Fixer (1 rule per commit)
- [x] Remove `composer.lock` from git.
- [x] Use Grumphp through `drupol/php-conventions`
- [ ] Investigate new PSalm issue => Issue found at https://github.com/marcosh/lamphpda/pull/8/commits/5b96f67e5d4f3f9f9af64411d9a42d5d4d0757c1#diff-c47877df3fa66c92b52cb2730c3b1876b765b1acf1339aa942138e1a6e6f85c4R21 - Is this a PSalm issue?

### CODE REVIEW

**Comment by marcosh** [comment]
I added the `.editorconfig` already.

I don't see any harm in leaving the `composer.lock` there, as soon as we test also for highest and lowest dependencies.

Moreover, it would be nice to add checks for some more things (`static` callables, callables return types, ...) both as a bash script in the `bin` folder and as a CI check

**Comment by drupol** [comment]
> I added the `.editorconfig` already.

:+1: 
 
> I don't see any harm in leaving the `composer.lock` there, as soon as we test also for highest and lowest dependencies.

Fair enough, your choice :)

> Moreover, it would be nice to add checks for some more things (`static` callables, callables return types, ...) both as a bash script in the `bin` folder and as a CI check

This could definitely be done through Grumphp (props @veewee !), if we use `drupol/php-conventions`, the rules are already there to check for these.

**Comment by drupol** [comment]
@marcosh I rebased this PR, you might be able to cherry-pick the commit you like.

**Comment by drupol** [comment]
Excellent!

There is also this commit which worth adding: https://github.com/marcosh/lamphpda/pull/8/commits/c94342bbb54dfe51a4fe611b61cfafcb94840bcd

WDYT ?

**Comment by drupol** [comment]
Yes and no.

There are risky rules in php-cs-fixer that might do it, but it's "risky" and I would not rely on an automated process for doing such things.

**Comment by marcosh** [comment]
well, we have tests and Psalm to check that the code actually works, so I'll be fine at least trying... which rules are those?

**Comment by drupol** [comment]
These rules:

* https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/function_notation/phpdoc_to_param_type.rst
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/function_notation/phpdoc_to_return_type.rst

I already tried them in this PR before deciding to not use them because they are creating inconsistencies.

**Comment by marcosh** [comment]
ah, I see, they do not recognize templates... not bearable in a project like this one

**Comment by marcosh** [comment]
cherry-picked your commit, thanks!

**Comment by drupol** [comment]
excellent :)

**Pull request closed without merging**
