### PR TITLE
introduce Maybe::withLazyDefault()

### PR DESCRIPTION
**Pull request by someniatko**
refs https://github.com/marcosh/lamphpda/issues/39

### CODE REVIEW

**Comment by someniatko** [comment]
But frankly, I'd made the second arg of the `lazyEval()` optional, then we won't need `withLazyDefault()` at all.

**Comment by marcosh** [comment]
I would entirely remove `lazyEval`

**Comment by someniatko** [comment]
I thought the logic is if `withDefault()` is representable in terms of `eval()` - it even was implemented by calling `eval()` - then `withLazyDefault()` should also be representable in terms of something similar. I just gave `withDefault()` / `withLazyDefault()` their separate implementations, because otherwise it looks like "stackframe madness" to me, considering I implement non-lazy variants using lazy (similar to how sync functions are often implemented using async)

**Comment by marcosh** [comment]
`Maybe a` is a [coproduct](https://www.wikiwand.com/en/Coproduct) between `a` and `()` and, by definition, it has a unique eliminator, which is `eval`. Every function which consumes a `Maybe` could be implemented in terms of it.

I would like to keep it this way in this library, with a single eliminator (i.e. `eval`) for every sum type, and several combinators implemented in terms of it.

**Comment by marcosh** [comment]
Thanks for the update!

> We are getting closer to pure lambda-calculus here ;)

Yes, this library is quite opinionated and theory-oriented :grin:

Personally, I would like to think a little whether to keep your optimized version or be more coherent with the rest of the codebase and use directly the reference implementation. @drupol thoughts?

**Comment by marcosh** [comment]
@someniatko I'd like to have the lazy version in the library.

I'm just not sure whether to keep your optimized version or implement the lazy version in terms on the strict one

**Comment by drupol** [comment]
Hey, I didn't mean to offend, and I'm sorry if that was the case.

As I said, I don't have the theoretical background and it's not me who is going to decide in this case.

**Comment by marcosh** [comment]
@someniatko sorry for the confusion. My :+1: was just an acknoledgment.

I'll reopen it

**Comment by marcosh** [comment]
I run a little benchmark to compare the two lazy implementations

```php
/**
     * @param callable(): A $a
     * @return A
     */
    public function withLazyDefault(callable $a)
    {
        // This can be implemented in terms of eval(), however the actual implementation is optimized:
        // return $this->eval($ifNothing, fn($value) => fn() => $ifJust($value))();

        /**
         * @psalm-suppress ImpureFunctionCall
         */
        return $this->isJust
            ? $this->value
            : $a();
    }

    /**
     * @param pure-callable(): A $a
     * @return A
     */
    public function withLazyDefault1(callable $a)
    {
        return $this->eval(
            $a,
            /**
             * @param A $value
             * @return pure-callable(): A
             */
            fn($value) => fn() => $value
        )();
    }
```

```php
it('runs withDefault and withLazyDefault on nothing', function () {
        $maybe = Maybe::nothing();

        $start = microtime(true);

        for ($i = 0; $i <= 100000; $i++) {
            $maybe->withLazyDefault(fn() => 42);
        }

        $middle = microtime(true);

        for ($i = 0; $i <= 100000; $i++) {
            $maybe->withLazyDefault1(fn() => 42);
        }

        $end = microtime(true);

        var_dump(sprintf('lazy %f, lazy1 %f', $middle - $start, $end - $middle));
    });
```

Expecially in the `just` case, the performance overhead of the reference implementation in quite high (2,5x times). With this in mind I'm ok with merging the optimized version and keeping the comment which refers to the other

**Comment by marcosh** [comment]
thanks @someniatko for this and for your patience!

**Comment by drupol** [comment]
Thanks indeed ! It's nice to see how we came to something that satisfies both sides :-)

Keep contributions coming!

**Pull request merged**
